n_estimators: 1000
max_depth: 6
learning_rate: 0.1
subsample: 0.9
colsample_bytree: 0.9
reg_lambda: 1.0
objective: multi:softprob
eval_metric: mlogloss
tree_method: hist
random_state: 42
early_stopping_rounds: 10
