apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          args:
            - mlflow
            - server
            - --backend-store-uri
            - sqlite:////mlflow/mlflow.db
            - --default-artifact-root
            - file:/mlflow/artifacts
            - --host
            - 0.0.0.0
            - --port
            - "5000"
          envFrom:
            - configMapRef:
                name: tickets-env
                optional: true
          ports:
            - containerPort: 5000
              name: http
          volumeMounts:
            - mountPath: /mlflow
              name: mlflow-storage
      volumes:
        - name: mlflow-storage
          persistentVolumeClaim:
            claimName: mlflow-data
