apiVersion: v1
kind: Secret
metadata:
  name: tickets-secrets
type: Opaque
stringData:
  MINIO_ROOT_USER: "replace-with-minio-root-user"
  MINIO_ROOT_PASSWORD: "replace-with-minio-root-password"
  REDIS_PASSWORD: "replace-with-redis-password"
