defaults:
  - data: minio
  - catboost: defaults
  - dnn: defaults
  - xgboost: defaults
  - logging: defaults
  - tfidf: defaults
  - _self_


project_name: tickets
seed: 42


redis_host: localhost
redis_port: 6379

split:
  - train: 0.7
  - val: 0.15
  - test: 0.15
