services:
  minio:
    image: minio/minio
    command: server /data --console-address :9001
    env_file:
      - ../.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?MINIO_ROOT_USER is not set}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?MINIO_ROOT_PASSWORD is not set}
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mlflow:
    image: ghcr.io/mlflow/mlflow
    command: >-
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root file:/mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    env_file:
      - ../.env
    volumes:
      - ./data/mlflow:/mlflow
    ports:
      - "5001:5000"

  redis:
    image: redis/redis-stack-server:latest
    env_file:
      - ../.env
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD:?REDIS_PASSWORD is not set}"
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:?REDIS_PASSWORD is not set}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
