gbrt_params:
  n_estimators: 1000
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.9
  colsample_bytree: 0.9
  reg_lambda: 1.0
  objective: multi:softprob
  eval_metric: mlogloss
  random_state: 42
  early_stopping_rounds: 10
  tree_method: gpu_hist
  predictor: gpu_predictor
  device: cuda
grid_search:
  enabled: true
  cv: 3
  scoring: f1_macro
  n_jobs: -1
  verbose: 2
  refit: f1_macro
  param_grid:
    n_estimators: [500, 1000]
    max_depth: [4, 6, 8]
    learning_rate: [0.05, 0.1]
    subsample: [0.8, 0.9, 1.0]
    colsample_bytree: [0.7, 0.9]
    reg_lambda: [0.5, 1.0]
